stages:
  - build

build:
  image: checkmk/check-mk-raw:2.0.0p5
  stage: build
  before_script:
    - su -c "mkdir -p ~/var/check_mk/packages/" -s /bin/sh cmk
    - su -c "./copy-to-target.sh" -s /bin/sh cmk
  script:
    - su -c 'source ~/.bashrc; cmk -P pack transceivers' -s /bin/bash cmk
    # test if mkp package exists
    - ls /omd/sites/cmk/transceivers-*.mkp
    - mv /omd/sites/cmk/transceivers-*.mkp .
  artifacts:
    paths:
      - transceivers-*.mkp 


